### ISSUE TITLE
Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by agauniyal** [richard1122/vscode-youcompleteme#1]
```
[Error - 3:09:08 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Error: connect ECONNREFUSED 127.0.0.1:41645
  Code: -32603 
```

**Comment by agauniyal** [comment]
On fresh start - 

```
[{"ycmd":{"path":"/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd","global_extra_config":"/home/agauniyal/.vim/.ycm_extra_conf.py","enabled_languages":["cpp","c"],"python":"/usr/bin/python"}}]
[onDidChangeConfiguration: [object Object]]
[getYcm: /home/agauniyal/projects/isaac-core, config: {"ycmd":{"path":"/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd","global_extra_config":"/home/agauniyal/.vim/.ycm_extra_conf.py","enabled_languages":["cpp","c"],"python":"/usr/bin/python"}}]
[getInstance] ycm is restarting
[start] data: 38835,d04
���MzUk,[object Object]
[processData: {"filepath_completion_use_working_dir":0,"auto_trigger":1,"min_num_of_chars_for_completion":2,"min_num_identifier_candidate_chars":0,"semantic_triggers":{},"filetype_specific_completion_to_disable":{"gitcommit":1},"seed_identifiers_with_syntax":0,"collect_identifiers_from_comments_and_strings":0,"collect_identifiers_from_tags_files":0,"max_num_identifier_candidates":10,"extra_conf_globlist":[],"global_ycm_extra_conf":"/home/agauniyal/.vim/.ycm_extra_conf.py","confirm_extra_conf":true,"complete_in_comments":0,"complete_in_strings":1,"max_diagnostics_to_display":30,"filetype_whitelist":{"*":1},"filetype_blacklist":{"tagbar":1,"qf":1,"notes":1,"markdown":1,"netrw":1,"unite":1,"text":1,"vimwiki":1,"pandoc":1,"infolog":1,"mail":1},"auto_start_csharp_server":1,"auto_stop_csharp_server":1,"use_ultisnips_completer":1,"csharp_server_port":0,"hmac_secret":"ZDA0DRmk1RkI2k16VcKBaw==","server_keep_logfiles":0,"gocode_binary_path":"","godef_binary_path":"","rust_src_path":"","racerd_binary_path":"","python_binary_path":"","rustSrcPath":""}]
[start] optionsFile: /tmp/VSCodeYcmOptions-1473673950159
[_start] [ '/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd',
  '--port=38835',
  '--options_file=/tmp/VSCodeYcmOptions-1473673950159',
  '--idle_suicide_seconds=600' ]
[_start] process spawn success 7256
[ycm stderr] Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/__main__.py", line 197, in <module>
    Main()
  File "/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/__main__.py", line 162, in Main
    extra_conf_store.CallGlobalExtraConfYcmCorePreloadIfExists()
  File "/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py", line 73, in CallGlobalExtraConfYcmCorePreloadIfExists
    _CallGlobalExtraConfMethod( 'YcmCorePreload' )
  File "/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py", line 91, in _CallGlobalExtraConfMethod
    module = Load( global_ycm_extra_conf, force = True )
  File "/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/extra_conf_store.py", line 149, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/utils.py", line 388, in LoadPythonSource
    return importlib.machinery.SourceFileLoader( name, pathname ).load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/agauniyal/.vim/.ycm_extra_conf.py", line 2, in <module>
    import ycm_core
ImportError: dynamic module does not define module export function (PyInit_ycm_core)

[_start exit] 1
[start] ycm started: 7256
```

**Comment by agauniyal** [comment]
works fine with vim ycm plugin :confused:

**Comment by agauniyal** [comment]
okay solved, python3 was the source of problem since my `/usr/bin/python` points to python3 while `/usr/bin/python2` is actual python2 which ycm needs.
