### ISSUE TITLE
ycm fails with message 'Network failed'

### ISSUE THREAD

**Issue by artines1** [richard1122/vscode-youcompleteme#24]
ycm-language-server always outputs following messages when I try to type. My vscode version is "January 2017 (version 1.9)"

[Error - 11:27:32 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603

**Comment by agauniyal** [comment]
Yes same with me - 

```
[Error - 1:00:24 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:24 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:36 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:44 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:44 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:44 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:45 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:45 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:00:45 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
[Error - 1:01:00 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Network failed
  Code: -32603 
```

**Comment by roederw** [comment]
This issue is resolved in the Insider version of VSCode. Version 1.10.0-insider (1.10.0-insider)

**Comment by agauniyal** [comment]
@roederw if this a bug on vscode side then they should _atleast_ publish a minor release for this. It sometimes becomes annoying because the Output window keeps popping up and taking cursor control and we aren't able to type anything in the editor window.

**Comment by roederw** [comment]
@agauniyal Nobody in their right mind would patch a large piece of software for a minor bug affecting an extension, like this. They have a ship cycle and the fix will be included with the next release. Use the Insider build if you want the fix. If not, wait for the official release and disable the extension.

**Comment by agauniyal** [comment]
They've already published numerous fixes in minor releases earlier, right after they released a major version so this is absolutely possible. But I agree that some might wait for a month and disable the extension for now.

**Comment by tanis2000** [comment]
@agauniyal I've been following your suggestion to use this extension and I happened to stumble upon this very same issue. Do you know what part of the extension is failing by any chance? I guess that this error might as well be due to the wrong usage of some of the VSCode API even though the insider build is working. It would be nice to be able to patch it on our own in the meanwhile

**Comment by agauniyal** [comment]
@tanis2000 I'm also using the insiders build for now.

**Comment by tanis2000** [comment]
1.10.0-insider still has this very same bug. It looks like what broke 1.9 also affected the current 1.10 Insider build.

**Comment by agauniyal** [comment]
@tanis2000 did this get resolved for your when upgrading to Feb build of vscode? For me it didn't so @richard1122 could you take a look at this?

**Comment by tanis2000** [comment]
@agauniyal nope, I'm still experiencing this issue as well.

**Comment by richard1122** [comment]
@agauniyal @tanis2000 @roederw 
Hi, I 've updated extension to version 1.0.26 and try to fix this issue.

Could you please update extension and see if there are any errors now? 

Thanks!

**Comment by agauniyal** [comment]
@richard1122 
```
[start] ycm started: 26445
[Error - 10:14:09 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Still no compile flags, no completions yet.
  Code: -32603 
```

It still happens but now it's bit more clear to me, this happens in vim version of ycm too because it takes a while to parse each new buffer/file editor opens. The correct solution would be to not output them in Output panel(probably via a user config) otherwise the output pane just keeps opening randomly abrupting us from typing further code.

**Comment by agauniyal** [comment]
For more info, try changing config of this plugin - 
```
[Error - 10:13:02 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Still no compile flags, no completions yet.
  Code: -32603 
[onDidChangeConfiguration settings] {"ycmd":{"confirm_extra_conf":true,"debug":true,"enabled_languages":["cpp","c"],"global_extra_config":"/home/agauniyal/.vim/.ycm_extra_conf.py","path":"/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd","python":"/usr/bin/python2","use_imprecise_get_type":true}}
[getInstance] ycm is restarting
[buildRequest] document, null; position: null; event: null
[reset] TypeError: Cannot read property 'all' of null
    at YcmRequest.buildRequest (/home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycmRequest.js:137:23)
    at YcmRequest.<anonymous> (/home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycmRequest.js:94:33)
    at next (<anonymous>)
    at /home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycmRequest.js:7:71
    at __awaiter (/home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycmRequest.js:3:12)
    at YcmRequest.request (/home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycmRequest.js:85:16)
    at Ycm.<anonymous> (/home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycm.js:165:35)
    at next (<anonymous>)
    at /home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycm.js:7:71
    at __awaiter (/home/agauniyal/.vscode/extensions/RichardHe.you-complete-me-1.0.28/server/ycm.js:3:12)
[start] unused port: 34425
[start] random secret: 190e99351334adcf3966746a8b64e51c
[start] default options: {"filepath_completion_use_working_dir":0,"auto_trigger":1,"min_num_of_chars_for_completion":2,"min_num_identifier_candidate_chars":0,"semantic_triggers":{},"filetype_specific_completion_to_disable":{"gitcommit":1},"seed_identifiers_with_syntax":0,"collect_identifiers_from_comments_and_strings":0,"collect_identifiers_from_tags_files":0,"max_num_identifier_candidates":10,"extra_conf_globlist":[],"global_ycm_extra_conf":"","confirm_extra_conf":1,"complete_in_comments":0,"complete_in_strings":1,"max_diagnostics_to_display":30,"filetype_whitelist":{"*":1},"filetype_blacklist":{"tagbar":1,"qf":1,"notes":1,"markdown":1,"netrw":1,"unite":1,"text":1,"vimwiki":1,"pandoc":1,"infolog":1,"mail":1},"auto_start_csharp_server":1,"auto_stop_csharp_server":1,"use_ultisnips_completer":1,"csharp_server_port":0,"hmac_secret":"","server_keep_logfiles":0,"gocode_binary_path":"","godef_binary_path":"","rust_src_path":"","racerd_binary_path":"","python_binary_path":""}
[processData: {"filepath_completion_use_working_dir":0,"auto_trigger":1,"min_num_of_chars_for_completion":2,"min_num_identifier_candidate_chars":0,"semantic_triggers":{},"filetype_specific_completion_to_disable":{"gitcommit":1},"seed_identifiers_with_syntax":0,"collect_identifiers_from_comments_and_strings":0,"collect_identifiers_from_tags_files":0,"max_num_identifier_candidates":10,"extra_conf_globlist":[],"global_ycm_extra_conf":"/home/agauniyal/.vim/.ycm_extra_conf.py","confirm_extra_conf":true,"complete_in_comments":0,"complete_in_strings":1,"max_diagnostics_to_display":30,"filetype_whitelist":{"*":1},"filetype_blacklist":{"tagbar":1,"qf":1,"notes":1,"markdown":1,"netrw":1,"unite":1,"text":1,"vimwiki":1,"pandoc":1,"infolog":1,"mail":1},"auto_start_csharp_server":1,"auto_stop_csharp_server":1,"use_ultisnips_completer":1,"csharp_server_port":0,"hmac_secret":"GQ6ZNRM0rc85ZnRqi2TlHA==","server_keep_logfiles":0,"gocode_binary_path":"","godef_binary_path":"","rust_src_path":"","racerd_binary_path":"","python_binary_path":"","rustSrcPath":""}]
[start] optionsFile: /tmp/VSCodeYcmOptions-1488732237293
[_start] [ '/home/agauniyal/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd',
  '--port=34425',
  '--options_file=/tmp/VSCodeYcmOptions-1488732237293',
  '--idle_suicide_seconds=600' ]
[_start] process spawn success 26445
[start] ycm started: 26445
[Error - 10:14:09 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Still no compile flags, no completions yet.
  Code: -32603 
```

**Comment by richard1122** [comment]
@agauniyal Hi, I just released an version. Added a workaround of this issue currently.

I think we fixed this.  Please update the extension.

Thanks!!

**Comment by agauniyal** [comment]
@richard1122 initial impressions are looking good, I'm using it for 10 mins and so far the bug hasn't shown up. I'll test a bit more and report back tomorrow but for now I guess you've fixed it 👍 . @tanis2000 could you test the latest release as well?

**Comment by tanis2000** [comment]
@agauniyal I confirm it's working fine for me as well.
