### ISSUE TITLE
ycm is unable to work, RuntimeError appears

### ISSUE THREAD

**Issue by uli2k** [richard1122/vscode-youcompleteme#48]
[_request] req.end called
[ycm stderr] 2017-09-12 12:07:31,165 - INFO - Received command request
Traceback (most recent call last):
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/handlers.py", line 86, in RunCompleterCommand
    request_data ) )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/completer.py", line 277, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 116, in <lambda>
    self._GoTo( request_data ) ),
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 187, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.

[_request] status code: 500
[_request] {"exception": {"TYPE": "RuntimeError"}, "traceback": "Traceback (most recent call last):
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/third_party/bottle/bottle.py\", line 861, in _handle
    return route.call(**args)
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/third_party/bottle/bottle.py\", line 1734, in wrapper
    rv = callback(*a, **ka)
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/watchdog_plugin.py\", line 100, in wrapper
    return callback( *args, **kwargs )
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/hmac_plugin.py\", line 62, in wrapper
    body = callback( *args, **kwargs )
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/handlers.py\", line 86, in RunCompleterCommand
    request_data ) )
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/completer.py\", line 277, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py\", line 116, in <lambda>
    self._GoTo( request_data ) ),
  File \"/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py\", line 187, in _GoTo
    raise RuntimeError( 'Can\\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.
", "message": "Can't jump to definition or declaration."}
[onDefinition error] { exception: { TYPE: 'RuntimeError' },
  traceback: 'Traceback (most recent call last):
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/handlers.py", line 86, in RunCompleterCommand
    request_data ) )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/completer.py", line 277, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 116, in <lambda>
    self._GoTo( request_data ) ),
  File "/usr/share/code/resources/app/extensions/RichardHe.you-complete-me-1.0.36/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 187, in _GoTo
    raise RuntimeError( \'Can\\\'t jump to definition or declaration.\' )
RuntimeError: Can\'t jump to definition or declaration.
',
  message: 'Can\'t jump to definition or declaration.' }
[buildRequest] document, /home/shantengfei/catkin_ws/src/industrial_core/industrial_robot_client/src/generic_joint_streamer_node.cpp; position: [object Object]; event: null

**Comment by richard1122** [comment]
Looks ycmd is not working well. Can you provide more information?
